apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zcicd.fullname" . }}-project-service
  labels:
    {{- include "zcicd.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-service
spec:
  replicas: {{ .Values.projectService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: project-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: project-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: project-service
          image: "{{ .Values.global.imageRegistry }}{{ .Values.projectService.image.repository }}:{{ .Values.projectService.image.tag }}"
          imagePullPolicy: {{ .Values.projectService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /configs/config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.projectService.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "zcicd.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zcicd.fullname" . }}-project-service
  labels:
    {{- include "zcicd.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-service
spec:
  type: {{ .Values.projectService.service.type }}
  ports:
    - port: {{ .Values.projectService.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: project-service
    app.kubernetes.io/instance: {{ .Release.Name }}
