apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zcicd.fullname" . }}-quality-service
  labels:
    {{- include "zcicd.labels" . | nindent 4 }}
    app.kubernetes.io/name: quality-service
spec:
  replicas: {{ .Values.qualityService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: quality-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quality-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: quality-service
          image: "{{ .Values.global.imageRegistry }}{{ .Values.qualityService.image.repository }}:{{ .Values.qualityService.image.tag }}"
          imagePullPolicy: {{ .Values.qualityService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.qualityService.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "zcicd.fullname" . }}-config
            - secretRef:
                name: {{ include "zcicd.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.qualityService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zcicd.fullname" . }}-quality-service
  labels:
    {{- include "zcicd.labels" . | nindent 4 }}
    app.kubernetes.io/name: quality-service
spec:
  type: {{ .Values.qualityService.service.type }}
  ports:
    - port: {{ .Values.qualityService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: quality-service
    app.kubernetes.io/instance: {{ .Release.Name }}
